### ISSUE TITLE
How to generate the document pair dataset?

### ISSUE THREAD

**Issue by XSilverBullet** [BangLiu/ArticlePairMatching#10]
I want to ask about how to assign document pair to label  ? 
Crowdsourcing or other ways?

**Comment by BangLiu** [comment]
@XSilverBullet Hi, basically we need to first construct a clustering dataset, and then generate document pair dataset from it. It needs human effort.

**Comment by XSilverBullet** [comment]
Thank you very  much!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
