### ISSUE TITLE
请问可以放出完整版的代码吗？

### ISSUE THREAD

**Issue by TommyWongww** [BangLiu/ArticlePairMatching#13]
想问下aggregation layer那里的term based similarity以及Bert做encode层部分代码会放出来吗？
另外就是这里没考虑用pytorch的自带dataloader作为数据加载吗，这样整个模型的Batchsize这部分不好调整

**Comment by TommyWongww** [comment]
还有就是现在batch 为1 大于1的情况有考虑吗

**Comment by BangLiu** [comment]
Please refer to HuggingFace's Transformers for Bert-based encoding. We directly utilized their implementation and the Chinese models.

For batchsize, we only test 1 to avoid padding issue. But you can add padding and test batchsize > 1.

**Comment by TommyWongww** [comment]
ok. thx.
