### ISSUE TITLE
No such file or directory: '../../../data/processed/event-story-cluster/same_event_doc_pair.no_cd.json'

### ISSUE THREAD

**Issue by loveJasmine** [BangLiu/ArticlePairMatching#2]
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/ArticlePairMatching/src/models/CCIG$ python3.6 main.py --data_type "event" --use_gfeatures
device is cpu
begin loading W2V............
Company
W2V loaded! 
Vocab size: 2, Embedding size: 200
Namespace(adjacent='tfidf', beta1=0.8, beta2=0.999, betweenness_threshold_coef=1.0, combine_type='separate', data_type='event', dropout_siamese=0.1, dropout_vfeat=0.1, ema_decay=0.9999, epochs=10, gcn_type='valina', gfeatures_type='features', hidden_final=16, hidden_siamese=128, hidden_vfeat=16, inputdata='event-story-cluster/same_event_doc_pair.no_cd.json', lr=0.001, lr_warm_up_num=1000, max_c_size=6, max_grad_norm=5.0, min_c_size=2, no_cuda=False, no_grad_clip=False, num_data=1000000000, num_gcn_layers=2, outputresult='event-story-cluster/same_event_doc_pair.no_cd.result.txt', pool_type='mean', seed=42, use_cd=False, use_ema=False, use_gcn=False, use_gfeatures=True, use_siamese=False, use_vfeatures=False, vertice='pagerank')
begin loading DATA............../../../data/processed/event-story-cluster/same_event_doc_pair.no_cd.json
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    labels, idx_train, idx_val, idx_test = load_graph_data(path, word_to_ix, MAX_LEN, args.num_data)
  File "/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/ArticlePairMatching/src/models/CCIG/loader.py", line 81, in load_graph_data
    fin = open(path, "r", encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: '../../../data/processed/event-story-cluster/same_event_doc_pair.no_cd.json'
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/ArticlePairMatching/src/models/CCIG$

**Comment by BangLiu** [comment]
Please go to src/models/CCIG/data/ and run feature_extractor.py.

**Comment by BangLiu** [comment]
You need to install graph-tool library first.
https://graph-tool.skewed.de/

**Comment by loveJasmine** [comment]
it looks graph-tool doesn't support ubuntu16

**Comment by BangLiu** [comment]
The installation of graph-tool is a nightmare.....
Give me another chance, I will definitely choose networkx......

**Comment by loveJasmine** [comment]
yes, i try install it from source, but it require c++17 which also doesn't support by ubuntu 16

**Comment by loveJasmine** [comment]
> The installation of graph-tool is a nightmare.....
> Give me another chance, I will definitely choose networkx......

maybe you can add networkx as an option

**Comment by BangLiu** [comment]
Maybe an older version of graph-tool can be installed

**Comment by rashibudati** [comment]
Is the code using networkx in public?
