### ISSUE TITLE
   File "C:\Users\username\Downloads\ArticlePairMatching-master\src\models\CCIG\data\resource_loader.py", line 53, in load_W2V_VOCAB     W2V_VOCAB = pickle.load(open(W2V_VOCAB_PKL_FILE, 'rb'))  UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by rashibudati** [BangLiu/ArticlePairMatching#20]
I get this error.

**Comment by BangLiu** [comment]
The pickle files need to be generated locally.

**Comment by rashibudati** [comment]
oh i see. I tried to generate the file. turns out the .model file which I cloned from github was not of complete size. However, even after manually downloading the .model file and generating the pickle file, I get the following error..

  File "C:\Users\BUD3KOR\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 53: character maps to <undefined>

Can you please tell why is it so? Is it because the file is corrupted ?
