### ISSUE TITLE
How to get ner word by textrank?

### ISSUE THREAD

**Issue by SCAUapc** [BangLiu/ArticlePairMatching#22]
Hi ! I love your work !  I want to use it on other dataset, but i don't know how you get the ner words. Would you tell me ? Thanks!
In the papaer, it said "Given a document D, we ﬁrst extract the named entities and keywords by TextRank".
Did you use TextRank to get keywords, and then match whether the key words in your own word-type dictionary?
e.g. 广东 in your dictionary is "广东-site".So when you get "广东" is a keyword, you search it and find it is a "site"? Or you use other ner tools? I need a good and fast ner method...Can you tell me about that?
Thanks for listen to me.

**Comment by BangLiu** [comment]
@SCAUapc Thank you for your interest in our work. TextRank is only suitable for keyword extraction. You can actually replace it with any other methods that are more suitable for your own dataset. For NER words, I also recommend to use NLP off-the-shelf tools based on your own dataset (e.g., StanfordNLP, SpaCy, etc.). Besides, most of the tools can be further improved by your own dictionary.

**Comment by SCAUapc** [comment]
@BangLiu Thank you for so quickly to answer my question ! Thanks , I got it.
