### ISSUE TITLE
Question about Encoding Local Matching Vectors

### ISSUE THREAD

**Issue by light8lee** [BangLiu/ArticlePairMatching#3]
As proposed in your paper, you generated local matching vectors in each concept, but what if the concept only contains sentences from one document, do you just ignore these concepts?

**Comment by BangLiu** [comment]
In this case, the other sentence is "empty".
Besides, we can add a feature to indicate whether each node contains sentences from both document, or just from one document.

**Comment by light8lee** [comment]
What happens if the other sentence is "empyt"

**Comment by BangLiu** [comment]
When the other sentence is empty, the difference shall be significant: we are now matching a sentence from document A with zero vectors (PAD embedding).

**Comment by light8lee** [comment]
Thank you for your reply.
