### ISSUE TITLE
关于graph-tool的问题

### ISSUE THREAD

**Issue by Amoto1103** [BangLiu/ArticlePairMatching#34]
运行feature_extractor.py时出现
python: symbol lookup error: /home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/graph_tool/draw/libgraph_tool_draw.so: undefined symbol: _ZN5Cairo7Context16select_font_faceERKSsNS_9FontSlantENS_10FontWeightE
请问这个如何解决？

**Comment by nxznm** [comment]
@Amoto1103 您好！请问您问题解决了吗，我也遇到类似的问题，会出现undefined_symbol。

**Comment by Amoto1103** [comment]
> 

emmm我已经放弃这个了，还是Google吧，像是graph tool这个包的.so的问题

**Comment by Amoto1103** [comment]
> @Amoto1103 您好！请问您问题解决了吗，我也遇到类似的问题，会出现undefined_symbol。

emmm我已经放弃这个了，还是Google吧，像是graph tool这个包的.so的问题
