### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by tingwt** [BangLiu/ArticlePairMatching#4]
def load_IDF(data):
    if data == "event_story":
        datafile = "../../../../data/raw/event-story-cluster/event_story_cluster.txt"
        contentfile = "../../../../data/processed/event-story-cluster/content.txt"
        idffile = "../../../../data/processed/event-story-cluster/IDF.txt"

I meet mistakes : these three txt  no such file or directory

**Comment by BangLiu** [comment]
I uploaded IDF.txt now. You don't need datafile and contentfile. Just need idffile.
